### PR TITLE
Add `Ord` instance

### PR DESCRIPTION
**Pull request by srid**
Enables NanoID to be used as a Map key.

### CODE REVIEW

**Comment by MichelBoucey** [comment]
I think `NanoID` must be kept opaque in itself so that one can't deduce something by seeing one of them. In other words, from randomness nothing should be deductible.

**Comment by srid** [comment]
@MichelBoucey I don't understand how your comment relates to adding `Ord` instance.

**Comment by MichelBoucey** [comment]
If some kind of things are ordered, they have relative positions that one can deduce by knowing the principle of the order.

**Comment by srid** [comment]
Afraid I still don't understand what you are saying. Perhaps if you demonstrate the problem ("randomness nothing should be deductible", "one can deduce by knowing the principle of the order") in terms of Haskell code, it would be clarifying.

**Comment by MichelBoucey** [comment]
Perhaps it would be clearer for you, by reading this blog post, [NanoID - A URL Friendly Unique Identifier](https://apoorvtyagi.tech/nanoid-url-friendly-unique-id): **NanoIDs are not sequential**.

**Comment by srid** [comment]
@MichelBoucey I don't see how non-sequentiality affects the ordering property. UUID is non-sequential as well, yet it [has `Ord`](https://hackage.haskell.org/package/uuid-1.3.15/docs/Data-UUID.html).

**Comment by MichelBoucey** [comment]
FYI : https://github.com/ai/nanoid/discussions/435

**Pull request closed without merging**
